import torch
from torch.utils.data import Dataset, DataLoader
import torch.optim as optim
from model import NeuralTheorizer 
import os

class OTIBDataset(Dataset):
    def __init__(self, data_file):
        if not os.path.exists(data_file):
            raise FileNotFoundError(f"Dataset {data_file} not found. Run data_preprocessing.py first.")
        # Data saved as a list of dicts: {'x': tensor, 'y': tensor, 'program': list}
        self.data = torch.load(data_file)
        
    def __len__(self):
        return len(self.data)
        
    def __getitem__(self, idx):
        # Pass the 3x32x32 images directly without flattening
        x = self.data[idx]['x']
        y = self.data[idx]['y']
        return x, y

def main():
    # Hyperparameters
    batch_size = 64
    learning_rate = 1e-3
    epochs = 50
    weight_decay = 1e-4
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Executing training on {device}...")
    
    # Load the training data generated by data_preprocessing.py
    dataset = OTIBDataset('otib_train_cifar10.pt')
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True, num_workers=4)
    
    # Initialize NEO Model 
    # num_primitives=8 matches the 8 transforms in ImageEditingPrimitives
    model = NeuralTheorizer(
        latent_dim=256, 
        num_primitives=8, 
        max_steps=3
    ).to(device)
    
    optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay)
    
    # Training Loop
    model.train()
    for epoch in range(epochs):
        total_loss = 0
        for batch_idx, (x, y) in enumerate(dataloader):
            x, y = x.to(device), y.to(device)
            
            optimizer.zero_grad()
            loss = model.compute_loss(x, y)
            
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()
            
            total_loss += loss.item()
            
            if batch_idx % 50 == 0:
                print(f"Epoch {epoch+1} | Batch {batch_idx}/{len(dataloader)} | Loss: {loss.item():.4f}")
                
        avg_loss = total_loss / len(dataloader)
        print(f"=== Epoch [{epoch+1}/{epochs}] Complete | Average Loss: {avg_loss:.4f} ===")
        
    torch.save(model.state_dict(), 'neo_cifar10_weights.pth')
    print("Training sequence completed and weights successfully saved.")

if __name__ == "__main__":
    main()